# Generated by Django 6.0.2 on 2026-03-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Узнать id: @userinfobot в Telegram', unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=128, verbose_name='Username в Telegram')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ разрешён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Разрешённый пользователь',
                'verbose_name_plural': 'Разрешённые пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
