# Generated by Django 6.0.2 on 2026-03-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweduser',
            name='fio',
            field=models.CharField(blank=True, help_text='Фамилия Имя Отчество', max_length=255, verbose_name='ФИО'),
        ),
    ]
