# Generated by Django 6.0.2 on 2026-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_add_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=128, verbose_name='Username в Telegram')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первое обращение')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последнее обращение')),
            ],
            options={
                'verbose_name': 'Обращение к боту',
                'verbose_name_plural': 'Обращения к боту (уникальные пользователи)',
                'ordering': ['-last_seen'],
            },
        ),
    ]
