# Generated by Django 6.0.2 on 2026-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_add_bot_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('done', 'Выполнено'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Пометка администратора')),
            ],
            options={
                'verbose_name': 'Запрос на удаление ПД',
                'verbose_name_plural': 'Запросы на удаление ПД',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='alloweduser',
            name='consent_at',
            field=models.DateTimeField(blank=True, help_text='Заполняется при принятии пользователем политики в боте', null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
        migrations.AddField(
            model_name='alloweduser',
            name='consent_version',
            field=models.CharField(blank=True, default='1.0', max_length=32, verbose_name='Версия политики при согласии'),
        ),
    ]
