# Generated by Django 6.0.2 on 2026-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_pd_compliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpravkaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('unit', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('rank', models.CharField(blank=True, max_length=255, verbose_name='Специальное звание')),
                ('signature_name', models.CharField(blank=True, help_text='Формат "И.И.Иванов"', max_length=255, verbose_name='ФИО для подписи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Профиль для справки',
                'verbose_name_plural': 'Профили для справок',
                'ordering': ['-updated_at'],
            },
        ),
    ]
